name: Build RSS

on:
  schedule:
    # GitHub cron is UTC. 05:00 UTC ≙ 06:00 in Europe/Rome (standard time).
    # In summer (CEST), this runs at 07:00 local.
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 playwright
          playwright install chromium

      - name: Build RSS
        run: python build_rss.py

      - name: Commit rss.xml (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "update rss" || echo "No changes"
          git push

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
