name: Build RSS

on:
  schedule:
    # 06:00 Europe/Rome (standard time), 07:00 in summer — GitHub uses UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Playwright browsers + all required system dependencies.
      - name: Install Playwright (browsers & deps)
        uses: microsoft/playwright-github-action@v1
        with:
          # chromium is enough for this project
          browsers: 'chromium'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 playwright

      - name: Build site & feeds
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -euo pipefail
          python build_rss.py

      - name: Commit site files (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html rss_tables.xml rss.xml || true
          git commit -m "update site & feeds" || echo "No changes"
          git push || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Always upload debug artifacts so we can inspect page content if something goes wrong
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            debug.html
            debug.png
            playwright_console.log
          if-no-files-found: ignore

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
