name: Build RSS
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install beautifulsoup4 requests
      - run: python build_rss.py

      - name: Commit RSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rss.xml || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update rss"
            git push origin HEAD:${{ github.ref_name }}
          fi

      - name: Prepare Pages artifact
        run: |
          if [ -f rss.xml ]; then
            mkdir -p public
            mv rss.xml public/rss.xml
            ls -la public
          else
            echo "rss.xml not found; nothing to upload"
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
