name: Build RSS
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

# Grant write permission to contents so GITHUB_TOKEN can push
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install beautifulsoup4 requests
      - run: python build_rss.py

      - name: Commit RSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          # Only commit & push if there are staged changes
          if ! git diff --staged --quiet; then
            git commit -m "update rss"
            # push back to the same branch (works when fetch-depth:0 and persist-credentials:true)
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: rss.xml

  deploy:
    needs: build
    permissions:
      pages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
