name: Build RSS
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install beautifulsoup4 requests
      - run: python build_rss.py

      - name: Prepare Pages artifact
        run: |
          if [ -f rss.xml ]; then
            mkdir -p public
            mv rss.xml public/rss.xml
            echo "Prepared public/rss.xml:"
            ls -l public/rss.xml
          else
            echo "rss.xml not found; failing intentionally."
            exit 1
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
